export const APP_ROUTES = {
  AUTH: {
    LOGIN: "/(auth)/login",
    REGISTER: "/(auth)/register-medecin",
    FORGOT_PASSWORD: "/(auth)/forgot-password",
    CHANGER_MOT_DE_PASSE: "/(auth)/changer-mot-de-passe",
  },
  MEDECIN: {
    REGISTER: "/(medecin)/register-medecin",
    HOME: "/(medecin)/(tabs)",
    PATIENT: {
      LISTE: "/(medecin)/(tabs)/patient/list",
      ADD: "/(medecin)/(tabs)/patient/add",
      DETAIL: "/(medecin)/(tabs)/patient/detail",
    },
    ORDONNANCE: {
      ADD: "/(medecin)/(tabs)/ordonnance/add",
      ADD_BY_PATIENT: "/(medecin)/(tabs)/ordonnance/add-by-patient",
      HISTORY: "/(medecin)/(tabs)/ordonnance/history",
      DETAIL: "/(medecin)/(tabs)/ordonnance/detail",
    },
    PARAMETRE: {
      PROFIL: "/(medecin)/(tabs)/parametre/profil",
    },
  },
  PATIENT: {
    REGISTER: "/(patient)/register-patient",
    HOME: "/(patient)/(tabs)",
    MES_RAPPELS: "/(patient)/(tabs)/rappels",
    PHARMACIES_GARDE: "/(patient)/(tabs)/pharmacies",
    PHARMACIES_MAP: "/(patient)/pharmacies-map",
  },
  ADMIN: {
    HOME: "/(admin)/(tabs)",
    UTILISATEURS: "/(admin)/(tabs)/utilisateurs",
    PROFIL: "/(admin)/(tabs)/profil",
    MEDECIN_ADD: "/(admin)/(tabs)/medecin-add",
    PATIENT_ADD: "/(admin)/(tabs)/patient-add",
    ADMIN_ADD: "/(admin)/(tabs)/admin-add",
    PHARMACIE_GARDE: "/(admin)/(tabs)/pharmacie-garde",
    PHARMACIE_GARDE_FORM: "/(admin)/(tabs)/pharmacie-garde-form",
    PHARMACIE_GARDE_DETAIL: "/(admin)/(tabs)/pharmacie-garde-detail",
    OCR: "/(admin)/(tabs)/ocr",
    DOSSIER_PATIENT: "/(admin)/(tabs)/dossier-patient",
    DOSSIER_MEDECIN: "/(admin)/(tabs)/dossier-medecin",
    COMPTE_DETAIL: "/(admin)/(tabs)/compte-detail",
    GRAPHES: "/(admin)/(tabs)/graphes",
    ETABLISSEMENTS: "/(admin)/(tabs)/etablissements",
    ETABLISSEMENT_FORM: "/(admin)/(tabs)/etablissement-form",
    PATIENT_TRANSFERT: "/(admin)/(tabs)/patient-transfert",
  },
} as const;
